# Define your own admin routes here
joram_admin_newsletter:
    resource: |
        alias: joram.newsletter
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: joram_admin_grid_newsletter
        vars:
            all:
                subheader: joram.ui.newsletters
                templates:
                    form: Newsletter/_form.html.twig
            index:
                icon: 'envelope outline'
    type: sylius.resource
    
joram_admin_newsletter_subscribers:
    resource: |
        alias: joram.newsletter_subscribers
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: joram_admin_grid_newsletter_subscribers
        vars:
            all:
                subheader: joram.ui.newsletter_subscribers
            index:
                icon: 'circular users'
    type: sylius.resource
