sylius_grid:
    grids:
        joram_admin_grid_newsletter:
            driver:
                name: doctrine/orm
                options:
                    class: Joram\SyliusNewsletterPlugin\Entity\Newsletter
            fields:
                subject:
                    type: string
                    label: sylius.ui.subject
                content:
                    type: string
                    label: sylius.ui.content
                    enabled: false
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
        joram_admin_grid_newsletter_subscribers:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Customer\Customer
            fields:
                user:
                    type: string
                    label: sylius.ui.subject
            actions:
                item:
                    delete:
                        type: delete
                    update:
                        type: update
            filters:
                subscription:
                    type: newsletter_subscription
    templates:
        filter:
            newsletter_subscription: 'Grid/Filter/newsletter_subscription.html.twig'
                        
sylius_resource:
    resources:
        joram.newsletter:
            driver: doctrine/orm
            classes:
                repository: Joram\SyliusNewsletterPlugin\Repo\NewsletterRepository
                form: Joram\SyliusNewsletterPlugin\Form\Type\NewsletterType
                model: Joram\SyliusNewsletterPlugin\Entity\Newsletter
            translation:
                classes:
                    model: Joram\SyliusNewsletterPlugin\Entity\NewsletterTranslation
                    form: Joram\SyliusNewsletterPlugin\Form\Type\NewsletterTranslationType
        joram.newsletter_subscribers:
            driver: doctrine/orm
            classes:
                repository: Sylius\Bundle\CoreBundle\Doctrine\ORM\CustomerRepository
                form: Sylius\Bundle\CustomerBundle\Form\Type\CustomerProfileType
                model: App\Entity\Customer\Customer
sylius_mailer:
    emails:
        joram_newsletter:
            subject: "Newsletter"
            template: 'Email/newsletter.html.twig'
            
framework:
    messenger:
        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage':  async
        transports:
            async: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        reset_on_message: true
