joram_newsletter_admin_routes:
    resource: "@JoramSyliusNewsletterPlugin/config/admin_routing.yaml"
    prefix: /admin

joram_newsletter_shop_routes:
    resource: "@JoramSyliusNewsletterPlugin/config/shop_routing.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
